--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OutiServer/Backup
build-by-default: true
branches:
- main
projects:
  Backup:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: KenCir/Commando/Commando
        version: ^3.1.0
...
