name: Backup
description: PMMPのバックアッププラグイン
version: 1.0.0
api: 4.0.0
main: outiserver\backup\Backup
src-namespace-prefix: outiserver\backup

permissions:
  backup.command:
    description: Backup Command Permission
    default: op